### ISSUE TITLE
bert_chinese_model：chinese_L-12_H-768_A-12

### ISSUE THREAD

**Issue by LiuYi217** [BI4O/rasa_milktea_chatbot#2]
您好，我不太了解bert 
请问bert_chinese_model：chinese_L-12_H-768_A-12要去哪里下载
bert-serving-start -model_dir path/to/chinese_L-12_H-768_A-12/ -num_worker=1

**Comment by BI4O** [comment]
请多使用百度
https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LiuYi217"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 下午3:17
收件人:&nbsp;"BI4O/rasa_milktea_chatbot"<rasa_milktea_chatbot@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[BI4O/rasa_milktea_chatbot] bert_chinese_model：chinese_L-12_H-768_A-12 (#2)




您好，我不太了解bert
 请问bert_chinese_model：chinese_L-12_H-768_A-12要去哪里下载
 bert-serving-start -model_dir path/to/chinese_L-12_H-768_A-12/ -num_worker=1
