### ISSUE TITLE
跑rasa train的時候出現的錯誤

### ISSUE THREAD

**Issue by WenTingTseng** [BI4O/rasa_milktea_chatbot#4]
你好，我在執行rasa train的時候出現以下錯誤，不太確定原因
`rasa.core.policies.ensemble.InvalidPolicyConfig: Module for policy 'policy.attention_policy.AttentionPolicy' could not be loaded. Please make sure the name is a valid policy.`

**Comment by BI4O** [comment]
我怀疑是你的policy文件夹缺失文件

**Comment by WenTingTseng** [comment]
我的policy文件夾內檔案都跟你github上的一樣，錯誤訊息中的`policy.attention_policy.AttentionPolicy`也存在呀，只是好像沒辦法被載入，因為invalid嗎
![擷取](https://user-images.githubusercontent.com/32416416/96445613-c78d4d80-1242-11eb-8d3c-9d3d6fd67a4e.JPG)
![擷取@](https://user-images.githubusercontent.com/32416416/96445617-c9571100-1242-11eb-8508-a6cfc5aaf329.JPG)

**Comment by WenTingTseng** [comment]
我剛剛重新安裝虛擬環境並裝套件上面問題沒有了，但是又出現新的問題
`AttributeError: module 'tensorflow._api.v1.keras.utils' has no attribute 'register_keras_serializable'`
這個是tensorflow版本的問題嗎，目前我是裝1.13.2

**Comment by WenTingTseng** [comment]
謝謝你，這個Bug已經解決了，主要應該是套件版本安裝上的問題。
